groups:
  - name: example_alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

      - alert: HighRequestLatencyP95FastAPI
        expr: histogram_quantile(0.95, sum(rate(fastapi_request_duration_seconds_bucket{job="example_fastapi_app"}[2m])) by (le, job)) > 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High P95 request latency on {{ $labels.job }}"
          description: "{{ $labels.job }} is experiencing high P95 request latency ({{ $value }}s)."

      - alert: HighErrorRateFastAPI
        expr: (sum(rate(fastapi_requests_total{job="example_fastapi_app", http_status=~"5.."}[5m])) by (job) / sum(rate(fastapi_requests_total{job="example_fastapi_app"}[5m])) by (job)) * 100 > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate on {{ $labels.job }}"
          description: "{{ $labels.job }} has an error rate of {{ $value | printf \"%.2f\" }}% over the last 5 minutes."