global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    - receiver: 'critical-receiver'
      match_re:
        severity: critical|emergency
      continue: true 

receivers:
  - name: 'default-receiver'
    webhook_configs:
      - url: 'http://localhost:9094/notifications' 
  - name: 'critical-receiver'
    webhook_configs:
      - url: 'http://localhost:9094/critical-notifications' 